name: Project Build
run-name: "ðŸ“¦ Project Build #${{ github.run_number }}"
on:
  push:
    branches:
      - master
env:
  JAVA_VERSION: 17

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:    
  setup:
    name: Setup Modpack Modern
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          repository: TerraFirmaGreg-Team/Modpack-Modern
          path: ./Modpack-Modern

      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build modpack
        run: |
          cd ./Modpack-Modern
          git checkout dev
          java -jar pakku.jar fetch
          #java -jar pakku.jar export

      - name: Setup HeadlessMc
        run: |
          mkdir -p run
          mv ./Modpack-Modern/mods ./run/
          mv ./Modpack-Modern/kubejs ./run/
          ls -l ./run/

      - name: Run MC test client
        timeout-minutes: 10
        uses: headlesshq/mc-runtime-test@4.1.0
        with:
          java: ${{ env.JAVA_VERSION }}
          mc: 1.20.1
          modloader: forge
          regex: .*forge.*
          fabric-api: none
          mc-runtime-test: lexforge
          headlessmc-command: -lwjgl --jvm "-Djava.awt.headless=true"
          xvfb: false