name: Project Build
run-name: "ðŸ“¦ Project Build #${{ github.run_number }}"
on:
  push:
    branches:
      - master
env:
  JAVA_VERSION: 21

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:    
  setup:
    name: Setup Modpack Modern
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Checkout TerraFirmaGreg/Modpack-Modern
        uses: actions/checkout@v5.0.0
        with:
          repository: TerraFirmaGreg-Team/Modpack-Modern
          path: ./Modpack-Modern

      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Pakku TerraFirmaGreg/Modpack-Modern
        run: |
          cd ./Modpack-Modern
          git checkout dev
          java -jar pakku.jar fetch
          java -jar pakku.jar export
          unzip ./build/serverpack/TerraFirmaGreg-Modern-DEV.zip ../out

      - name: Setup HeadlessMc
        run: |
          mkdir -p run
          unzip ./Modpack-Modern/build/serverpack/TerraFirmaGreg-Modern-DEV.zip ./run
          ls -l
          ls -l ./run/
          mv ./Modpack-Modern/mods ./
          mv ./Modpack-Modern/kubejs ./

      - name: Run MC test server
        timeout-minutes: 10
        uses: headlesshq/mc-server-test@1.1.0
        with:
          java: ${{ env.JAVA_VERSION }}
          mc: 1.20.1
          modloader: forge