name: Project Build
run-name: "ðŸ“¦ Project Build #${{ github.run_number }}"
on:
  push:
    branches:
      - master
env:
  JAVA_VERSION: 21
  MINECRAFT_VERSION: 1.20.1
  LOADER_TYPE: forge
  LOADER_VERSION: 47.4.6

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Modpack Modern
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Checkout TerraFirmaGreg/Modpack-Modern
        uses: actions/checkout@v5.0.0
        with:
          repository: TerraFirmaGreg-Team/Modpack-Modern
          path: ./Modpack-Modern

      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Pakku Modpack
        run: |
          cd ./Modpack-Modern
          git checkout dev
          java -jar pakku.jar fetch
          java -jar pakku.jar export

      - name: Setup Minecraft Server
        run: |
          mkdir -p run
          unzip ./Modpack-Modern/build/serverpack/TerraFirmaGreg-Modern-DEV.zip -d run
          mv ./Modpack-Modern/mods ./
          mv ./Modpack-Modern/kubejs ./

      #- name: Run Minecraft Server
      #  run: |
      #    cd run
      #    java -jar minecraft_server.jar -Xmx2048M -Xms1024M nogui

      - name: Run MC test server
        timeout-minutes: 10
        uses: headlesshq/mc-server-test@1.1.0
        with:
          java: ${{ env.JAVA_VERSION }}
          mc: 1.20.1
          modloader: forge
          test-file: ./test.json